PocketScribe/PocketScribe/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PocketScribe.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PocketScribe/PocketScribe/Controllers/SharedTranscriptController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Diagnostics;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Mime;
using System.Text;
using System.Threading.Tasks;
using System.Web.WebPages;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using PocketScribe.Models;
using PocketScribe.ViewModels;

namespace PocketScribe.Controllers
{
    public class SharedTranscriptController : Controller
    {


        private ApplicationDbContext _context;

        public SharedTranscriptController()
        {
            _context = new ApplicationDbContext();
        }

        // GET: Shared
        public ActionResult Index()
        {
            var user = User.Identity.GetUserName();
            var transcripts = _context.Transcripts.Where(t => t.SharedUsersCollection.Select(x => x.User).Contains(user));

            return View(transcripts);
        }

        /// <summary>
        /// Gets the information from a single transcript for the main recording and modifying transcript page
        /// Also gets the list of that users transcripts for the collapsable sidebar
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize]
        public ActionResult Details(int id)
        {
            var transcript = _context.Transcripts.SingleOrDefault(t => t.Id == id);
            if (transcript == null)
            {
                return HttpNotFound();
            }
            var user = User.Identity.GetUserName();
            if (transcript.SharedUsersCollection.Select(x => x.User).Contains(user))
            {
                var transcripts = _context.Transcripts.Where(t => t.SharedUsersCollection.Select(x => x.User).Contains(user));
                var viewModel = new AllTranscipts()
                {
                    transcript = transcript,
                    Transcripts = transcripts
                };

                return View(viewModel);

            }
            else return HttpNotFound();

        }
    }
}

PocketScribe/PocketScribe/Controllers/TranscriptController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Mime;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using PocketScribe.Models;
using PocketScribe.ViewModels;


namespace PocketScribe.Controllers
{
    public class TranscriptController : Controller
    {

        private ApplicationDbContext _context;

        public TranscriptController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        /// <summary>
        /// GET: /transcript
        /// </summary>
        /// <returns>returns all the transcripts the user has already created</returns>
        [Authorize]
        public ViewResult Index()
        {
            var user = User.Identity.GetUserName();
            var transcripts = _context.Transcripts.Where(t => t.UserName == user);
            return View(transcripts);
        }

        /// <summary>
        /// Creates a new transcript, adds it to database, then redirects user to that transcript page
        /// </summary>
        [HttpPost]
        [Authorize]
        public void Create()
        {

            var date = DateTime.Now;
            var user = User.Identity.GetUserName();
            var transcript = new Transcript() { Date = date, Name = "MyTranscript", UserName = user };
            var transcripts = _context.Transcripts.Where(t => t.UserName == user);
            _context.Transcripts.Add(transcript);
            _context.SaveChanges();
            var id = transcript.Id;
            transcript.Name = "MyTranscript" + id;
            _context.SaveChanges();
            Response.Redirect("~/Transcript/Details/" + id);
        }
        /// <summary>
        /// Gets the information from a single transcript for the main recording and modifying transcript page
        /// Also gets the list of that users transcripts for the collapsable sidebar
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize]
        public ActionResult Details(int id)
        {
            var transcript = _context.Transcripts.SingleOrDefault(t => t.Id == id);
            if (transcript == null)
            {
                return HttpNotFound();
            }
            if (transcript.UserName == User.Identity.Name.ToString())
            {
                var user = User.Identity.GetUserName();
                var transcripts = _context.Transcripts.Where(t => t.UserName == user);
                var viewModel = new AllTranscipts()
                {
                    transcript = transcript,
                    Transcripts = transcripts
                };

                return View(viewModel);

            }
            else return HttpNotFound();

        }
        /// <summary>
        /// When the start recording button is hit, change the started value to true
        /// </summary>
        /// <param name="id">id of the transcript</param>
        [Authorize]
        public void StartRecording(int id)
        {
            var transcript = _context.Transcripts.SingleOrDefault(t => t.Id == id);
            transcript.started = true;
            _context.SaveChanges();
        }
        /// <summary>
        /// Once the stop recording button is hit, get the text that was transcribed and save it to the database for that specific transcription
        /// </summary>
        /// <param name="id">id of the transcription</param>
        /// <param name="text"> contains the entire transcription text</param>
        [Authorize]
        public void StopRecording(int id, string text)
        {

           var transcript = _context.Transcripts.SingleOrDefault(c => c.Id == id);
           transcript.Text = text;
           transcript.stopped = true;
           _context.SaveChanges();
           Details(id);
        }
        [Authorize]
        public void Rename(int id, string name)
        {
            var v = _context.Transcripts.SingleOrDefault(a => a.Id == id);
            v.Name = name;
            _context.SaveChanges();
        }

        [Authorize]
        public void EditText(int id, string text)
        {
            var v = _context.Transcripts.SingleOrDefault(a => a.Id == id);
            v.Text = text;
            _context.SaveChanges();
        }
        /// <summary>
        /// Adds users to the shared transcript list
        /// regexUtilities checks if the string given is a valid email address
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <param name="usersList"></param>
        [Authorize]
        public string Share(int id, string users)
        {

            List<string> usersList = users.Split(',').ToList<string>();
            List<string> returnList = new List<string>();
            var transcript = _context.Transcripts.SingleOrDefault(a => a.Id == id);
            foreach (var user in usersList)
            {
                var trimmedUser = user.Trim();
                if (trimmedUser != User.Identity.Name.ToString() && !trimmedUser.IsEmpty() && RegexUtilities.IsValidEmail(trimmedUser) && !transcript.SharedUsersCollection.Select(x => x.User).Contains(trimmedUser))
                {
                    var s = new Share()
                    {
                        TranscriptID = transcript.Id,
                        User = trimmedUser
                    };
                    transcript.SharedUsersCollection.Add(s);
                    returnList.Add(trimmedUser);
                }
            }
            _context.SaveChanges();
            return String.Join(", ", returnList);
        }

    }
}

PocketScribe/PocketScribe/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PocketScribe/PocketScribe/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PocketScribe/PocketScribe/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron text-center">
    <h1>PocketScribe</h1>
    <p class="lead">PocketScribe is a desktop and mobile application that converts speech audio to text in real-time.</p>
</div>

<div style="background-color: #66cdaa; padding-top: 20px; padding-bottom: 40px;">

    <div class="row" style="margin-bottom: 10px;">
        <div class="col-md-4" style="box-shadow: 10px 15px #888888; margin-top: 10px; margin-left: 10%; border-style:solid; border-color: black; border-radius: 20px; background-color: white;">
            <div>
                <h2 style="text-align: center;">Getting Started</h2>
                <p style="text-align: center;">
                    Start creating a transcription to convert your speech into text by simply clicking the "Start A New Transcription" button below.
                </p>
                <p>
                    @using (Html.BeginForm("Create", "Transcript"))
                    {
                        <button style="margin-left: 30%;" type="submit" class="btn-info">+ Start A New Transcription</button>
                    }
                </p>
            </div>
        </div>

        <div class="col-md-4" style="box-shadow: 10px 15px #888888; margin-top: 150px; margin-left: 10%; border-style:solid; border-color: black; border-radius: 20px; background-color: white;">
            <div>
                <h2 style="text-align: center;">Sharing Transcriptions</h2>
                <p style="text-align: center;"> You can easily share your transcriptions with anyone, which allows them to view and edit the transcription in real time.</p>
                <p style="text-align: center;">Click the button below to see which transcriptions are shared with you!</p>
                <p><button style="margin-left: 38%;" class="btn-info">@Html.ActionLink("Shared With Me", "Index", "SharedTranscript")</button></p>
            </div>
        </div>

    </div>
    <div style="box-shadow: 10px 15px #888888; width: 40%; margin-top: 0px; margin-left: 10%; border-style:solid; border-color: black; border-radius: 20px; background-color: white;">
        <h2 style="text-align: center;">Saving Transcriptions</h2>
        <p style="width: 75%; text-align: center; margin-left: 12%;">Transcriptions are automatically saved!!</p>
        <p style="width: 75%; text-align: center; margin-left: 12%;">However, if you truly desire to have the transcription saved on your computer, do not fret! From the click of a button, you have the power to download transcriptions onto your computer in multiple formats (Text and PDF currently supported).</p>
    </div>

</div>